fuse_subgraphs: False
fuse_ave_width: 0

distributed:
  logging:
    bokeh: critical

  admin:
    tick:
      limit: 5s

kubernetes:
  count:
    max: 40
  worker-template:
    metadata:
    spec:
      nodeSelector:
        dask-worker: True
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '5'
          - --death-timeout
          - '60' 
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-worker
        resources:
          limits:
            cpu: "7"
            memory: 32G
          requests:
            cpu: 5
            memory: 32G

labextension:
  factory:
    module: dask_kubernetes
    class: KubeCluster
    args: []
    kwargs: {}
